name: HiveBox Integration Tests
on:
  workflow_run:
    workflows: ["HiveBox CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t hive:latest .

      - name: Start Container
        run: docker run -d -p 5000:5000 --name hivebox-container hive:latest

      - name: Wait for service
        run: sleep 5

      - name: Run Integration Tests
        run: pytest src/integration_tests.py

      - name: Stop and Remove Container
        if: always()
        run: docker stop hivebox-container && docker rm hivebox-container
